apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: z5fgu3rgo-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/z5fgu3rgo-java-quarkus-gitops